version: 2.1
orbs:
  gor: hubci/goreleaser@2.4.0
jobs:
  test:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - restore_cache:
          key: go-mod-{{ checksum "go.sum" }}
      - run:
          name: Download Go modules
          command: go mod download
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/go/pkg/mod
      - run:
          name: Run tests
          command: gotestsum --junitfile junit.xml
      - store_test_results:
          path: junit.xml
workflows:
  main:
    jobs:
      - test
      - gor/release:
          version: 1.24.0
          go-version: '1.21.7'
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
